name: Rust
on: [push]

jobs:
  linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: aaa
        run: |
          gcc --version
          gcc-9 --version
          cmake --version
          type -a gcc
          
  mac:
    name: Build MacOS
    runs-on: macOS-latest
    steps:
      - name: a
        run: |
          type -a gcc
