name: Rust
on: [push]

jobs:
  linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: aaa
        run: |
          echo okasdasdasdas
          gcc --version
          gcc-9 --version
          cmake --version
          type -a gcc
          
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v2

          
  mac:
    name: Build MacOS
    runs-on: macOS-latest
    steps:
      - name: a
        run: |
          type -a gcc
          gcc --version
          gcc-9 --version
          cmake --version
          echo ag
          type -a clang
