name: Rust
on: [push]

jobs:
  linux:
    name: Build Linux ${{ matrix.config.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { arch: x86_64, bits: 64 }

    steps:
      - name: aaa
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc-8
          
          gcc --version
          cmake --version
