name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Release
      run: cargo build --release
      if: startsWith(github.event.ref, 'refs/tags/')
    - name: Release
      uses: fnkr/github-action-ghr@v1.1
      env:
        GHR_PATH: target/release/libgithub_actions_test.so
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: startsWith(github.event.ref, 'refs/tags/')


