name: Unity
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-MyProjectName-TargetPlatform
          restore-keys: |
            Library-MyProjectName-
            Library-
            
      - uses: webbertakken/unity-builder@v0.11
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2019.3.2f1
          targetPlatform: StandaloneWindows64
          
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
          
